services:
  test:
    build:
      context: .
      target: builder
    container_name: app-tests
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env.test
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
    networks:
      - app-network
    command: >
      sh -c "pnpm db:migrate && pnpm test"

  database:
    image: ankane/pgvector:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: random-stuff
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d random-stuff"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
